name: Push nuget
on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  nuget-publish:
    name: Build and push nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Kafka Docker containers
        run: |
          docker compose -f ./Rinkudesu.Kafka.Dotnet.IntegrationTests/docker-compose.yml up -d

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore, build, test
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet test -c Release --no-build

      - name: Pack nuget
        run: dotnet pack Rinkudesu.Kafka.Dotnet --no-build -p:PackageVersion=$GITHUB_REF_NAME -c Release -o ./out

      - name: Push to nuget.org
        run: dotnet nuget push "./out/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
